# Generated by Django 3.2.7 on 2021-11-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('female', 'female'), ('male', 'male')], max_length=30, null=True),
        ),
    ]
