# Generated by Django 3.2.7 on 2021-10-25 10:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211014_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dob',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date of Birth'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('female', 'female'), ('male', 'male')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
