# Generated by Django 3.2.7 on 2021-10-25 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211025_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dob',
            field=models.DateField(help_text='Date of Birth'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('information', 'information'), ('reminder', 'reminder')], max_length=50, null=True)),
                ('content', models.TextField(null=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'pending'), ('resolved', 'resolved')], default='pending', max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
    ]
