# Generated by Django 3.2.7 on 2021-10-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211025_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='picture',
            field=models.ImageField(null=True, upload_to='pictures/'),
        ),
    ]
