# Generated by Django 3.2.7 on 2021-11-13 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('doses', models.IntegerField(default=1)),
                ('approved', models.BooleanField(default=False)),
                ('added_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('center_level', models.CharField(choices=[('HC I', 'HC I'), ('HC II', 'HC II'), ('HC III', 'HC III'), ('HC IV', 'HC IV'), ('Regional Referal Hospital', 'Regional Referal Hospital'), ('National Hospital', 'National Hospital'), ('Private Hospital', 'Private Hospital')], default='Private Hospital', max_length=60, null=True)),
                ('contact', models.EmailField(max_length=254)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100, null=True)),
                ('contact', models.EmailField(max_length=254)),
                ('approved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jabbed_on', models.DateField()),
                ('dose', models.CharField(choices=[('soon', 'soon'), ('taken', 'taken'), ('missed', 'missed')], default='taken', max_length=30)),
                ('next_dose', models.DateField(blank=True, null=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jab.drug')),
                ('jabbed_at', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jab.facility')),
                ('jabbed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinator', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinatee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-jabbed_on'],
            },
        ),
        migrations.CreateModel(
            name='NextVaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jabbed_on', models.DateField()),
                ('dose', models.BooleanField(default=False)),
                ('next_dose', models.DateField(blank=True, null=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jab.drug')),
                ('init_vaccination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jab.vaccination')),
                ('jabbed_at', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jab.facility')),
                ('jabbed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nextvacc_medic', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='drug',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jab.manufacturer'),
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('serial', models.CharField(blank=True, max_length=50, null=True)),
                ('expiry', models.DateField()),
                ('approved', models.BooleanField(default=False)),
                ('added_on', models.DateTimeField(auto_now=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jab.drug')),
            ],
            options={
                'ordering': ['-expiry'],
            },
        ),
    ]
