# Generated by Django 3.2.7 on 2021-11-13 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jab', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Drug',
            new_name='Vaccine',
        ),
    ]
