# Generated by Django 3.2.7 on 2021-10-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jab', '0002_vaccination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccination',
            name='dose',
            field=models.CharField(choices=[('soon', 'soon'), ('taken', 'taken'), ('missed', 'missed')], default='soon', max_length=30),
        ),
    ]
