# Generated by Django 3.2.7 on 2021-10-28 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jab', '0003_alter_vaccination_dose'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='center_level',
            field=models.CharField(choices=[('HC I', 'HC I'), ('HC II', 'HC II'), ('HC III', 'HC III'), ('HC IV', 'HC IV'), ('Regional Referal Hospital', 'Regional Referal Hospital'), ('National Hospital', 'National Hospital'), ('Private Hospital', 'Private Hospital')], max_length=60, null=True),
        ),
        migrations.CreateModel(
            name='NextVaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jabbed_on', models.DateField()),
                ('dose', models.BooleanField(default=False)),
                ('next_dose', models.DateField(blank=True, null=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jab.vaccine')),
                ('init_vaccination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jab.vaccination')),
                ('jabbed_at', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jab.facility')),
                ('jabbed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nextvacc_medic', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
